import type { LedgerLine, Config } from "./types";
import { round2, fmtMoney, fmtMoneyGL, fmtDate } from "./helpers";

const WS_BLUE: [number, number, number] = [27, 102, 255];
const WS_LOGO_URL = "/workstream_logo.png";

export async function generatePDF(lines: LedgerLine[], config: Config): Promise<Uint8Array> {
  const { jsPDF } = await import("jspdf");
  const autoTableModule = await import("jspdf-autotable");
  const autoTable = autoTableModule.default || autoTableModule.autoTable;

  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  const topStart = 56;

  function addBranding(pageNum: number, totalPages: number) {
    const savedFontSize = doc.getFontSize();
    doc.setFillColor(...WS_BLUE);
    doc.rect(0, 0, pageWidth, 4, "F");
    doc.setTextColor(0, 0, 0);
    doc.setDrawColor(0, 0, 0);
    doc.setFillColor(0, 0, 0);
    doc.setFontSize(savedFontSize);
    const footerY = pageHeight - 28;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, footerY, pageWidth - margin, footerY);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(130, 130, 130);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, footerY + 12, { align: "right" });
    doc.text("Generated by Workstream", margin, footerY + 12);
    doc.setTextColor(0, 0, 0);
  }

  // Pages 1+: Journal Entry
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Journal Entry #${config.journalNo}`, margin, topStart);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Journal date:", margin, topStart + 16);
  doc.text(config.journalDate, margin + 58, topStart + 16);
  doc.text("Journal no.", pageWidth / 2, topStart + 16);
  doc.text(config.journalNo, pageWidth / 2 + 48, topStart + 16);

  const totalDebits = round2(lines.reduce((s, l) => s + l.debit, 0));
  const totalCredits = round2(lines.reduce((s, l) => s + l.credit, 0));

  const jeRows = lines.map((l) => [
    String(l.num),
    `${l.accountCode} ${l.accountName}`,
    l.debit ? fmtMoney(l.debit) : "",
    l.credit ? fmtMoney(l.credit) : "",
    l.description,
    l.name,
  ]);
  jeRows.push(["", "", fmtMoney(totalDebits), fmtMoney(totalCredits), "", ""]);

  autoTable(doc, {
    startY: topStart + 28,
    head: [["#", "ACCOUNT", "DEBITS", "CREDITS", "DESCRIPTION", "NAME"]],
    body: jeRows,
    theme: "plain",
    showHead: "everyPage",
    styles: { fontSize: 6.5, cellPadding: 2, font: "helvetica", overflow: "linebreak", halign: "left" },
    headStyles: { fillColor: [217, 217, 217], textColor: [0, 0, 0], fontStyle: "bold", fontSize: 6.5, halign: "left" },
    columnStyles: {
      0: { cellWidth: 24 },
      1: { cellWidth: 180 },
      2: { cellWidth: 60 },
      3: { cellWidth: 60 },
      4: { cellWidth: 105 },
      5: { cellWidth: contentWidth - 24 - 180 - 60 - 60 - 105 },
    },
    alternateRowStyles: { fillColor: [247, 247, 247] },
    margin: { left: margin, right: margin, top: topStart + 28, bottom: 48 },
    didParseCell: (data: any) => {
      if (data.section === "body") {
        if (data.column.index === 0 || data.column.index === 2 || data.column.index === 3) {
          data.cell.styles.halign = "right";
        }
        if (data.row.index === jeRows.length - 1) {
          data.cell.styles.fontStyle = "bold";
          data.cell.styles.fillColor = [255, 255, 255];
        }
      }
    },
  });

  // New page: General Ledger Report
  doc.addPage();
  let y = topStart;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("General Ledger Report", margin, y);
  y += 18;

  const nowStr = new Date().toISOString().replace("T", " ").slice(0, 19);
  const valX = margin + 170;

  doc.setFontSize(8);
  const metaRows: [string, string, string?, string?][] = [
    ["Client:", config.clientName, "CoA Map:", config.coaMap],
    ["GL File Name:", config.glFileName],
    ["Completion Date/Time:", nowStr],
    ["Last Download Attempt Date/Time:", "n/a"],
    ["File Specification:", config.coaMap],
  ];
  for (const row of metaRows) {
    doc.setFont("helvetica", "bold");
    doc.text(row[0], margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(row[1], valX, y);
    if (row[2] && row[3]) {
      doc.setFont("helvetica", "bold");
      doc.text(row[2], pageWidth / 2 + 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(row[3], pageWidth / 2 + 72, y);
    }
    y += 12;
  }
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("General Ledger Transactions", margin, y);
  y += 4;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  const glRows: string[][] = [];
  let glTotal = 0;

  for (const line of lines) {
    const signedAmount = line.debit - line.credit;
    glTotal += signedAmount;
    glRows.push([
      line.accountName,
      fmtMoneyGL(signedAmount),
      fmtDate(line.date),
      line.class,
      line.docNum,
      line.memo || line.description,
      line.name,
    ]);
  }
  glRows.push(["Total:", fmtMoneyGL(round2(glTotal)), "", "", "", "", ""]);

  autoTable(doc, {
    startY: y,
    head: [["Account", "Amount", "Date", "Class", "DocNum", "Memo", "Name"]],
    body: glRows,
    theme: "grid",
    showHead: "everyPage",
    styles: { fontSize: 6, cellPadding: 1.5, font: "helvetica", overflow: "linebreak", lineColor: [200, 200, 200], lineWidth: 0.25, halign: "left" },
    headStyles: { fillColor: [217, 217, 217], textColor: [0, 0, 0], fontStyle: "bold", fontSize: 6, halign: "left" },
    bodyStyles: { fillColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: contentWidth * 0.28 },
      1: { cellWidth: contentWidth * 0.12 },
      2: { cellWidth: contentWidth * 0.12 },
      3: { cellWidth: contentWidth * 0.06 },
      4: { cellWidth: contentWidth * 0.07 },
      5: { cellWidth: contentWidth * 0.20 },
      6: { cellWidth: contentWidth * 0.15 },
    },
    margin: { left: margin, right: margin, top: topStart, bottom: 48 },
    didParseCell: (data: any) => {
      if (data.section === "body") {
        if (data.column.index === 1) {
          data.cell.styles.halign = "right";
        }
        if (data.row.index === glRows.length - 1) {
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  // Payroll source page
  doc.addPage();
  let pyY = topStart;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("This GL file contains data from the following payrolls:", margin, pyY);
  pyY += 14;

  autoTable(doc, {
    startY: pyY,
    head: [["Company", "Service Center", "Year/Week Number", "Pay Date", "Batch Number"]],
    body: [[
      config.companyName,
      "",
      "",
      fmtDate(config.journalDate),
      config.payrollId || "",
    ]],
    theme: "grid",
    styles: { fontSize: 7, cellPadding: 3, font: "helvetica", lineColor: [200, 200, 200], lineWidth: 0.25 },
    headStyles: { fillColor: [217, 217, 217], textColor: [0, 0, 0], fontStyle: "bold", fontSize: 7 },
    margin: { left: margin, right: margin },
  });

  // Apply branding
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addBranding(i, totalPages);
  }

  // Post-process with pdf-lib for logo
  const jsPdfBytes = new Uint8Array(doc.output("arraybuffer") as ArrayBuffer);

  try {
    const { PDFDocument } = await import("pdf-lib");
    const pdfDoc = await PDFDocument.load(jsPdfBytes);

    const logoResponse = await fetch(WS_LOGO_URL);
    const logoBytes = new Uint8Array(await logoResponse.arrayBuffer());

    const logoImage = await pdfDoc.embedPng(logoBytes);
    const logoW = 110;
    const logoH = logoImage.height * (logoW / logoImage.width);
    const logoTopFromPage = 4 + (52 - logoH) / 2;

    const pages = pdfDoc.getPages();
    for (const page of pages) {
      const { width, height } = page.getSize();
      page.drawImage(logoImage, {
        x: width - margin - logoW,
        y: height - logoTopFromPage - logoH,
        width: logoW,
        height: logoH,
      });
    }

    return await pdfDoc.save();
  } catch (err) {
    console.warn("Logo embedding failed — PDF generated without logo", err);
    return jsPdfBytes;
  }
}
